<?php

define("CODIGO_USUARIO_CREADO", "201");
define("CODIGO_USUARIO_EXISTE", "501");
define("CODIGO_FALTAN_PARAMETROS", "400");
define("CODIGO_ERROR_LOGIN","403");
define("CODIGO_SESION_FACEBOOK_CADUCADA","601");
define("CODIGO_SESION_FACEBOOK_ERRONEA","602");
define("CODIGO_ERROR","500");
define("CODIGO_OK","200");
define("CODIGO_NUEVA_CUENTA","603");






define("ESTATUS_OK",200);
define("ESTATUS_FORBIDDEN",403);
define("ESTATUS_INTERNAL_SERVER_ERROR",500);
define("ESTATUS_BAD_REQUEST",400);
define("ESTATUS_CREATED",201);
define("ESTATUS_CONFLICTO",409);

?>